### ISSUE TITLE
How to get more than 100 results?

### ISSUE THREAD

**Issue by yrik** [EdmundMartin/SearchScraperAPI#3]

**Comment by EdmundMartin** [comment]
Currently, it doesn't support scraping multiple pages. I may add this as a feature at a later date. PR requests welcome.

**Comment by EdmundMartin** [comment]
@yrik I have started working on separate library, which supports multiple page scraping. I will eventually refactor this code base to make use of the other library. You can find the other library [here](https://github.com/EdmundMartin/search_it). Let me know if you have any questions.

**Comment by EdmundMartin** [comment]
I have refactored to make use of the search_it library and the project now supports scraping multiple pages with a sleep.
